import type { MetadataRoute } from "next"
import { INTRO_VIDEO, PROGRAM_PREVIEW_VIDEOS } from "@/lib/video-data"
import { TOOLKIT_TOOLS } from "@/lib/toolkit-tools"

const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}` : "http://localhost:3000")

function isoDurationToSeconds(duration: string): number {
  const match = duration.match(/PT(?:(\d+)M)?(?:(\d+)S)?/)
  const minutes = match?.[1] ? Number.parseInt(match[1], 10) : 0
  const seconds = match?.[2] ? Number.parseInt(match[2], 10) : 0
  return minutes * 60 + seconds
}

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: siteUrl,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 1,
      images: [`${siteUrl}/hero-data-center.jpg`, `${siteUrl}/logo.png`],
      videos: [
        {
          title: INTRO_VIDEO.title,
          thumbnail_loc: INTRO_VIDEO.thumbnailUrl,
          description: INTRO_VIDEO.description,
          content_loc: `https://www.youtube.com/watch?v=${INTRO_VIDEO.id}`,
          player_loc: `https://www.youtube.com/embed/${INTRO_VIDEO.id}`,
          duration: isoDurationToSeconds(INTRO_VIDEO.duration),
          publication_date: INTRO_VIDEO.uploadDate,
          family_friendly: "yes",
        },
      ],
    },
    {
      url: `${siteUrl}/about`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.6,
      images: [`${siteUrl}/modern-tech-classroom.png`],
    },
    {
      url: `${siteUrl}/demo`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${siteUrl}/engineers-toolkit`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
      images: [`${siteUrl}/engineers-toolkit-hero.jpg`],
    },
    ...TOOLKIT_TOOLS.map((tool) => ({
      url: `${siteUrl}/engineers-toolkit/${tool.slug}`,
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.7,
      images: [`${siteUrl}/engineers-toolkit-hero.jpg`],
    })),
    {
      url: `${siteUrl}/simulations/generator-physics-simulator.html`,
      lastModified: new Date("2026-07-29"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${siteUrl}/simulations/electron-drift-simulator.html`,
      lastModified: new Date("2026-07-29"),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${siteUrl}/programs/electrical-design-data-center`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
      images: [`${siteUrl}/electrical-design-data-center.jpg`],
      videos: PROGRAM_PREVIEW_VIDEOS.map((video) => ({
        title: video.title,
        thumbnail_loc: video.thumbnailUrl,
        description: video.description,
        content_loc: `https://www.youtube.com/watch?v=${video.id}`,
        player_loc: `https://www.youtube.com/embed/${video.id}`,
        duration: isoDurationToSeconds(video.duration),
        publication_date: video.uploadDate,
        family_friendly: "yes" as const,
      })),
    },
    {
      url: `${siteUrl}/data-center-design`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.9,
      images: [`${siteUrl}/hero-data-center.jpg`],
    },
    {
      url: `${siteUrl}/resources/data-center-engineering-career-roadmap`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${siteUrl}/resources/data-center-commissioning-handover-checklist`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${siteUrl}/programs/autocad-training`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
      images: [`${siteUrl}/autocad-training.png`],
    },
    {
      url: `${siteUrl}/programs/bim-revit-training`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
      images: [`${siteUrl}/bim-training.jpg`],
    },
    {
      url: `${siteUrl}/programs/computer-skills-applications`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
      images: [`${siteUrl}/computer-training-ms-office.png`],
    },
    {
      url: `${siteUrl}/blog`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${siteUrl}/blog/ups-sizing-data-center-worked-example`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-ups-topologies.jpg`],
    },
    {
      url: `${siteUrl}/blog/voltage-drop-calculation-formula-examples`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-cable-sizing.jpg`],
    },
    {
      url: `${siteUrl}/blog/generator-sizing-data-center-worked-example`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-ups-topologies.jpg`],
    },
    {
      url: `${siteUrl}/blog/data-center-load-calculation-it-load-to-utility-demand`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-mv-lv-distribution.jpg`],
    },
    {
      url: `${siteUrl}/blog/power-factor-correction-capacitor-bank-sizing`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-mv-lv-distribution.jpg`],
    },
    {
      url: `${siteUrl}/blog/short-circuit-calculation-basics-lv-systems`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-ct-pt-relay.jpg`],
    },
    {
      url: `${siteUrl}/blog/sts-vs-ats-data-center-transfer-switches`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-redundancy-explained.jpg`],
    },
    {
      url: `${siteUrl}/blog/what-is-a-data-center-components-and-how-it-works`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/hero-data-center.jpg`],
    },
    {
      url: `${siteUrl}/blog/ups-battery-sizing-autonomy-time-worked-example`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-ups-topologies.jpg`],
    },
    {
      url: `${siteUrl}/blog/cable-tray-sizing-fill-calculation-example`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-cable-sizing.jpg`],
    },
    {
      url: `${siteUrl}/blog/busduct-vs-cable-data-center-power-distribution`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-mv-lv-distribution.jpg`],
    },
    {
      url: `${siteUrl}/blog/types-of-data-centers-enterprise-colocation-hyperscale-edge`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/hero-data-center.jpg`],
    },
    {
      url: `${siteUrl}/blog/hyperscale-vs-colocation-data-centers`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/hero-data-center.jpg`],
    },
    {
      url: `${siteUrl}/blog/data-center-cooling-systems-explained`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-hot-cold-aisle.jpg`],
    },
    {
      url: `${siteUrl}/blog/crah-vs-crac-data-center-cooling-units`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-hot-cold-aisle.jpg`],
    },
    {
      url: `${siteUrl}/blog/chilled-water-vs-air-cooled-data-center-cooling`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-hot-cold-aisle.jpg`],
    },
    {
      url: `${siteUrl}/blog/wue-water-usage-effectiveness-explained`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-pue-explained.jpg`],
    },
    {
      url: `${siteUrl}/blog/data-center-commissioning-levels-explained`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-protection-relay.jpg`],
    },
    {
      url: `${siteUrl}/blog/fat-sat-ist-testing-data-center-explained`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-protection-relay.jpg`],
    },
    {
      url: `${siteUrl}/blog/liquid-cooling-direct-to-chip-vs-immersion`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-hot-cold-aisle.jpg`],
    },
    {
      url: `${siteUrl}/blog/mv-switchgear-data-center-ratings-and-selection`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-mv-lv-distribution.jpg`],
    },
    {
      url: `${siteUrl}/blog/lv-switchgear-and-mcc-basics-data-center`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-mv-lv-distribution.jpg`],
    },
    {
      url: `${siteUrl}/blog/data-center-earthing-design-tn-s-bonding`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-earthing-bonding.jpg`],
    },
    {
      url: `${siteUrl}/blog/lightning-protection-data-center-basics`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-earthing-bonding.jpg`],
    },
    {
      url: `${siteUrl}/blog/protection-coordination-basics-data-center`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-protection-relay.jpg`],
    },
    {
      url: `${siteUrl}/blog/load-flow-study-explained-data-center`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-single-line-diagram.jpg`],
    },
    {
      url: `${siteUrl}/blog/harmonics-in-data-centers-sources-and-mitigation`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-ct-pt-relay.jpg`],
    },
    {
      url: `${siteUrl}/blog/arc-flash-basics-data-center-engineers`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-protection-relay.jpg`],
    },
    {
      url: `${siteUrl}/blog/data-center-lighting-design-lux-calculation-example`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-cable-sizing.jpg`],
    },
    {
      url: `${siteUrl}/blog/electrical-load-schedule-how-to-build-one`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-single-line-diagram.jpg`],
    },
    {
      url: `${siteUrl}/blog/tia-942-explained-rated-1-to-rated-4`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-tier-classification.jpg`],
    },
    {
      url: `${siteUrl}/blog/uptime-institute-tier-certification-what-it-covers`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-tier-classification.jpg`],
    },
    {
      url: `${siteUrl}/blog/iec-60364-data-center-electrical-installations`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-mv-lv-distribution.jpg`],
    },
    {
      url: `${siteUrl}/blog/is-3043-earthing-code-summary`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-earthing-bonding.jpg`],
    },
    {
      url: `${siteUrl}/blog/ashrae-thermal-guidelines-data-centers-explained`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-hot-cold-aisle.jpg`],
    },
    {
      url: `${siteUrl}/blog/nfpa-75-and-76-fire-protection-it-spaces`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-hot-cold-aisle.jpg`],
    },
    {
      url: `${siteUrl}/blog/ai-data-centers-explained`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/hero-data-center.jpg`],
    },
    {
      url: `${siteUrl}/blog/high-density-racks-power-distribution-implications`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-pdu-explained.jpg`],
    },
    {
      url: `${siteUrl}/blog/gpu-cluster-infrastructure-for-electrical-engineers`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/hero-data-center.jpg`],
    },
    {
      url: `${siteUrl}/blog/800-vdc-data-center-power-explained`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-ups-vs-generator.jpg`],
    },
    {
      url: `${siteUrl}/blog/ai-vs-traditional-data-center-electrical-design`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-single-line-diagram.jpg`],
    },
    {
      url: `${siteUrl}/blog/data-center-bim-why-it-matters`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/bim-training.jpg`],
    },
    {
      url: `${siteUrl}/blog/revit-electrical-basics-for-engineers`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/bim-training.jpg`],
    },
    {
      url: `${siteUrl}/blog/cable-tray-modeling-in-revit`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/bim-training.jpg`],
    },
    {
      url: `${siteUrl}/blog/revit-electrical-families-creating-and-managing`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/bim-training.jpg`],
    },
    {
      url: `${siteUrl}/blog/navisworks-clash-detection-workflow`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/bim-training.jpg`],
    },
    {
      url: `${siteUrl}/blog/dynamo-for-electrical-engineers-revit`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/bim-training.jpg`],
    },
    {
      url: `${siteUrl}/blog/lod-bim-level-of-development-explained`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/bim-training.jpg`],
    },
    {
      url: `${siteUrl}/blog/bim-coordination-meeting-process`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/bim-training.jpg`],
    },
    {
      url: `${siteUrl}/blog/as-built-bim-data-centers`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/bim-training.jpg`],
    },
    {
      url: `${siteUrl}/blog/revit-vs-autocad-for-electrical-design`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/bim-training.jpg`],
    },
    {
      url: `${siteUrl}/blog/revit-mep-course-syllabus-and-outcomes`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/bim-training.jpg`],
    },
    {
      url: `${siteUrl}/blog/autocad-electrical-drawing-for-beginners`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/autocad-training.png`],
    },
    {
      url: `${siteUrl}/blog/data-center-electrical-engineer-salary-india`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-electrical-engineer-career.jpg`],
    },
    {
      url: `${siteUrl}/blog/data-center-engineer-skills-roadmap`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-electrical-engineer-career.jpg`],
    },
    {
      url: `${siteUrl}/blog/data-center-jobs-uae-saudi-arabia-electrical-engineers`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-electrical-engineer-career.jpg`],
    },
    {
      url: `${siteUrl}/blog/data-center-engineer-interview-questions-electrical`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-electrical-engineer-career.jpg`],
    },
    {
      url: `${siteUrl}/blog/data-center-certifications-what-is-worth-it`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-electrical-engineer-career.jpg`],
    },
    {
      url: `${siteUrl}/blog/mep-engineer-to-data-center-engineer-transition-guide`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-electrical-engineer-career.jpg`],
    },
    {
      url: `${siteUrl}/blog/fresher-electrical-engineer-first-year-in-data-centers`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-electrical-engineer-career.jpg`],
    },
    {
      url: `${siteUrl}/blog/commissioning-engineer-data-center-role-and-skills`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-electrical-engineer-career.jpg`],
    },
    {
      url: `${siteUrl}/blog/site-engineer-in-data-center-projects`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-electrical-engineer-career.jpg`],
    },
    {
      url: `${siteUrl}/blog/etap-for-data-center-design-where-it-fits`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-single-line-diagram.jpg`],
    },
    {
      url: `${siteUrl}/blog/how-to-read-a-data-center-electrical-drawing-set`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-single-line-diagram.jpg`],
    },
    {
      url: `${siteUrl}/blog/what-is-dcim-and-do-you-need-it`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/hero-data-center.jpg`],
    },
    {
      url: `${siteUrl}/blog/data-center-architecture-spaces-layers-and-layout`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-redundancy-explained.jpg`],
    },
    {
      url: `${siteUrl}/blog/green-data-centers-efficiency-levers`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-pue-explained.jpg`],
    },
    {
      url: `${siteUrl}/blog/renewable-energy-for-data-centers`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-ups-vs-generator.jpg`],
    },
    {
      url: `${siteUrl}/blog/battery-energy-storage-in-data-centers`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-ups-topologies.jpg`],
    },
    {
      url: `${siteUrl}/blog/lithium-ion-vs-vrla-batteries-for-ups`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-ups-topologies.jpg`],
    },
    {
      url: `${siteUrl}/blog/data-center-site-selection-power-availability`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/hero-data-center.jpg`],
    },
    {
      url: `${siteUrl}/blog/data-center-electrical-design-course-what-to-look-for`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/electrical-design-data-center.jpg`],
    },
    {
      url: `${siteUrl}/blog/data-center-glossary-terms-engineers-use`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/hero-data-center.jpg`],
    },
    {
      url: `${siteUrl}/blog/hv-cable-sizing-calculation-worked-example`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-cable-sizing.jpg`],
    },
    {
      url: `${siteUrl}/blog/earth-conductor-sizing-adiabatic-equation-example`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-cable-sizing.jpg`],
    },
    {
      url: `${siteUrl}/blog/transformer-cable-sizing-parallel-cables-example`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-cable-sizing.jpg`],
    },
    {
      url: `${siteUrl}/blog/neutral-conductor-sizing-harmonics-data-centers`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-cable-sizing.jpg`],
    },
    {
      url: `${siteUrl}/blog/current-transformer-ratio-burden-selection-example`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-ct-pt-relay.jpg`],
    },
    {
      url: `${siteUrl}/blog/overcurrent-relay-settings-idmt-worked-example`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-protection-relay.jpg`],
    },
    {
      url: `${siteUrl}/blog/ups-selection-criteria-what-to-specify`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-ups-topologies.jpg`],
    },
    {
      url: `${siteUrl}/blog/single-line-diagrams-explained`,
      lastModified: new Date("2026-08-26"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-single-line-diagram.jpg`],
    },
    {
      url: `${siteUrl}/blog/pdu-power-distribution-unit-explained`,
      lastModified: new Date("2026-08-26"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-pdu-explained.jpg`],
    },
    {
      url: `${siteUrl}/blog/ups-topologies-explained`,
      lastModified: new Date("2026-08-26"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-ups-topologies.jpg`],
    },
    {
      url: `${siteUrl}/blog/redundancy-n-n1-2n-explained`,
      lastModified: new Date("2026-08-26"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-redundancy-explained.jpg`],
    },
    {
      url: `${siteUrl}/blog/pue-power-usage-effectiveness-explained`,
      lastModified: new Date("2026-08-26"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-pue-explained.jpg`],
    },
    {
      url: `${siteUrl}/blog/hot-aisle-cold-aisle-containment-explained`,
      lastModified: new Date("2026-08-26"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-hot-cold-aisle.jpg`],
    },
    {
      url: `${siteUrl}/blog/data-center-tier-classification-explained`,
      lastModified: new Date("2026-08-26"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-tier-classification.jpg`],
    },
    {
      url: `${siteUrl}/blog/how-to-become-a-data-center-electrical-design-engineer-in-india`,
      lastModified: new Date("2026-07-14"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-electrical-engineer-career.jpg`],
    },
    {
      url: `${siteUrl}/blog/cable-sizing-basics-for-data-center-electrical-design`,
      lastModified: new Date("2026-07-24"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-cable-sizing.jpg`],
    },
    {
      url: `${siteUrl}/blog/ups-vs-diesel-generator-data-center-backup-power`,
      lastModified: new Date("2026-07-24"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-ups-vs-generator.jpg`],
    },
    {
      url: `${siteUrl}/blog/mv-lv-power-distribution-architecture-explained`,
      lastModified: new Date("2026-07-24"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-mv-lv-distribution.jpg`],
    },
    {
      url: `${siteUrl}/blog/earthing-and-bonding-basics-for-data-centers`,
      lastModified: new Date("2026-07-24"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-earthing-bonding.jpg`],
    },
    {
      url: `${siteUrl}/blog/current-transformer-explained`,
      lastModified: new Date("2026-09-17"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-ct-pt-relay.jpg`],
    },
    {
      url: `${siteUrl}/blog/potential-transformer-explained`,
      lastModified: new Date("2026-09-17"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-potential-transformer.jpg`],
    },
    {
      url: `${siteUrl}/blog/protection-relay-explained`,
      lastModified: new Date("2026-09-17"),
      changeFrequency: "monthly",
      priority: 0.7,
      images: [`${siteUrl}/data-center-protection-relay.jpg`],
    },
    {
      url: `${siteUrl}/resources/data-center-design-basics-checklist`,
      lastModified: new Date("2026-07-24"),
      changeFrequency: "monthly",
      priority: 0.6,
      images: [`${siteUrl}/electrical-design-data-center.jpg`],
    },
  ]
}
